apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: spring19824 
  janus-idp.io/tekton: spring19824
  backstage.io/kubernetes-id: spring19824
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spring19824
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  