apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: spring19824-gitops
  description: This is GitOps manifest for spring19824   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: spring19824
    janus-idp.io/tekton: spring19824
    backstage.io/kubernetes-id: spring19824 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:spring19824
