apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: spring19824
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring19824 
  name: spring19824
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spring19824
    weight: 100 
