apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spring19824
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring19824 
  name: spring19824
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spring19824 
